### ISSUE TITLE
Version should be 0.4.26

### ISSUE THREAD

**Issue by platocrat** [orangewit3/supply_chain_simulator#1]
https://github.com/orangewit3/supply_chain_simulator/blob/27101de936873e50b476814f0c815cb0c79a16ce/supplyChain.sol#L1

Version number must be changed from 0.4.20 to 0.4.26 to avoid compiler errors

**Comment by platocrat** [comment]
@orangewit3 can you please fix this already?

I had to update it in my own branch, but we should all already have the correct version when making any new branches and forks

**Comment by orangewit3** [comment]
I'll put up a pr for this after Nakuls code gets pushed

**Comment by platocrat** [comment]
> I'll put up a pr for this after Nakuls code gets pushed

Do you put a PR for this yet?

**Comment by platocrat** [comment]
Fixed
